<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>rescue_javascript_in_public Unit Test</title>
	
	<script type="text/javascript" src="../../lib/scriptaculous-js-1.8.2/lib/prototype.js"></script>
	<script type="text/javascript" src="../../lib/scriptaculous-js-1.8.2/src/scriptaculous.js"></script>
	<script type="text/javascript" src="../../lib/scriptaculous-js-1.8.2/src/unittest.js"></script>
	<script type="text/javascript" src="../../lib/lowpro-0.5/lowpro.js"></script>
	<script type="text/javascript" src="../../lib/drnic_js_test_helpers/src/ajax_mock/prototype.js"></script>
	<script type="text/javascript" src="../../lib/drnic_js_test_helpers/src/simulate_events.js"></script>
	<script type="text/javascript" src="../../lib/modalbox1.6.0/modalbox.js"></script>
	<script type="text/javascript" src="../../rescue_javascript_in_public.js"></script>
	<link rel="stylesheet" href="../../lib/modalbox1.6.0/modalbox.css" type="text/css" />
	
	<link rel="stylesheet" href="../../lib/scriptaculous-js-1.8.2/test/test.css" type="text/css" />
	
	<style type="text/css" media="screen">
	</style>
	<script type="text/javascript" language="javascript" charset="utf-8">
	// <![CDATA[
      Event.addBehavior.reassignAfterAjax = true;
      Event.addBehavior({
	      'a#test-button:click' : function(e){
          nonExistentVar.methodCall();
        }
      });
  </script>
	
</head>

<body>
	<h1 id="1">rescue_javascript_in_public Unit Test</h1>
	
	<!-- Log output -->
	<div id="testlog"> </div>
	
	<br />
	
	<!-- Tests follow -->
	<script type="text/javascript" language="javascript" charset="utf-8">
	// <![CDATA[
		new Test.Unit.Runner({

		setup: function(){ with(this) {
      // mock out Ajax request
      testCase = this
      testCase.requestToRescueJavascriptInPublicWasMade = false
      Test.Ajax.setupMock(RescueJavascriptInPublic.url, function(request, response) {
        response.status = 500;
        response.body = "The response back from the server should be a 500 error"
        testCase.requestToRescueJavascriptInPublicWasMade = true;
        testCase.request = request;
      });

      // mock out method that reloads the page
      RescueJavascriptInPublic.afterMessageHasBeenRead = function(){};
		}},

		teardown: function(){with(this) {
      Test.Ajax.clearMocks()
		}},

    // We can't actually throw an error to test this as the unit testing
    // framework would fail the test. Instead, we're just going to call the handler
    // to make sure it works
		testRescueOnError: function() { with(this) {
      var message = "Exception Occurred";
      var uri = "app?go=yes";
      var line = 12;
      RescueJavascriptInPublic.rescueOnError(message, uri, line);
      assert(this.requestToRescueJavascriptInPublicWasMade, "A request to " + RescueJavascriptInPublic.url + " should have been made");
      assertEqual('on_error', this.request.options.parameters['error']['error_type']);
      assertEqual(message, this.request.options.parameters['error']['message']);
      assertEqual(uri, this.request.options.parameters['error']['uri']);
      assertEqual(line, this.request.options.parameters['error']['line']);
      wait(4000, function(){}); // let the user close the dialog box
		}},

		testRescueOnPrototypeCallbackExceptions : function() { with(this) {
      new Ajax.Request("test.html", {method:"get", 
        onComplete: function(){
          // try to do something that doesn't work
          lsjfsdf().sdf();
        }
      });
      testCase = this;
      wait(4000, function(){
        assert(testCase.requestToRescueJavascriptInPublicWasMade, "A request to " + RescueJavascriptInPublic.url + " should have been made");
        assertEqual('ajax_callback_exception', this.request.options.parameters['error']['error_type']);
        assert(testCase.request.options.parameters['error']['stack'], "The stack dumped should be passed");
        assertMatch(/lsjfsdf is not defined/, testCase.request.options.parameters['error']['exception']);
      });
		}},

		testRescuePrototypeOnFailure : function() { with(this) {
      failedUrl = "failed_url"
      Test.Ajax.setupMock(failedUrl, function(request, response) {
        response.status = 500;
        response.responseText = "500 error message"
        request.options.onFailure(response);
      });
      new Ajax.Request(failedUrl, {
          onFailure: RescueJavascriptInPublic.rescueAjaxFailure.bind(RescueJavascriptInPublic)
        }
      );
      testCase = this;
      wait(4000, function(){
        assert(testCase.requestToRescueJavascriptInPublicWasMade, "A request to " + RescueJavascriptInPublic.url + " should have been made");
        assertEqual('ajax_on_failure', testCase.request.options.parameters['error']['error_type']);
        assertEqual("500 error message", testCase.request.options.parameters['error']['response']);
      });
    }},

		testShouldRescueErrorsWithEventHandlersIfUsingLowPro : function() { with(this) {
      Event.simulate('test-button', 'click'); // call our buggy event handler

      testCase = this;
      wait(4000, function(){
        assert(testCase.requestToRescueJavascriptInPublicWasMade, "A request to " + RescueJavascriptInPublic.url + " should have been made");
        assertEqual('event_handler_exception', testCase.request.options.parameters['error']['error_type']);
        assert(testCase.request.options.parameters['error']['stack'], "The stack dumped should be passed");
        assertMatch(/nonExistentVar is not defined/, testCase.request.options.parameters['error']['exception']);
      });
		}},


    /*
		testShouldRescueErrorIfCaughtAndPassedManually : function() { with(this) {
		}},
    */

		}, "testlog");
	// ]]>
	</script>
  <a id="test-button" href="#">test button</a>
</body>
</html>
